name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: bikudas8deakin/capstone-api:latest

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: gke-gcloud-auth-plugin

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials capstone-cluster --zone=us-central1-a --project=sit737-26t1-biku-das-f3a53f3

      - name: Deploy to GKE
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
        run: |
          kubectl apply -f deployment.yaml --validate=false
          kubectl rollout status deployment/capstone-api
